### ISSUE TITLE
JSON.parse error while processing "send" body response

### ISSUE THREAD

**Issue by mkomigor** [vacu/electron-google-analytics#1]
I have this error after I tried to use "analytics.screen" method without debug mode:
`Uncaught SyntaxError: Unexpected token G in JSON at position 0`

Response body is:
`GIF89a�����,D;`

So I think we need to check for this before you are doing JSON.parse(body).

Please take a look at screenshot:
https://www.dropbox.com/s/kreklzlktc34bwo/Screenshot%202017-02-23%2012.25.00.png?dl=0

**Comment by vacu** [comment]
Fixed in 0.0.11.
