### ISSUE TITLE
Session Duration 0

### ISSUE THREAD

**Issue by lequanghuylc** [vacu/electron-google-analytics#10]
When using this module the seassion duration in GA dashboard is always 0. How do I fix it? I only use pageview in each screen. My Electron app is a single page app built mostly with React.

**Comment by vacu** [comment]
Shouldn't affect the session duration, but I will add the "sc" param so you can control it.

**Comment by dnbard** [comment]
I'm experiencing same issue.

**Comment by buddythumbs** [comment]
Hi, I would also like to track this (have multiple pages in the app, react-router and redux). 

Even If i had an example of how the session duration "should" be checked then it would help.

I currently only use the pageview function also.

**Comment by vacu** [comment]
you can use this https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#sc
and thanks to https://github.com/vacu/electron-google-analytics/commit/cc6f2823e4f56dea48de9b18a7bd8f3c181a150c you can use the "set()"
