### ISSUE TITLE
Can'tset clientID

### ISSUE THREAD

**Issue by Ciao121** [vacu/electron-google-analytics#14]
Hi everyone. I'm using
```
const Analytics  = require('electron-google-analytics');
const analytics = new Analytics.default('UA-87670043-6');
analytics.set('uid', 123);
```
and I'm getting this error:
**analytics.set is not a function**

What am i doing wrong?
Thank you!!!

**Comment by mbackonja** [comment]
Hello @Ciao121 
The latest release on npm is v0.0.24 and my PR is merged after that, but @vacu did not release a new version with that implementation. Wait for @vacu to release v0.0.25 with `analytics.set` or install package from GitHub repository

**Comment by Ciao121** [comment]
Thank you very much! This was the problem!
