### ISSUE TITLE
Tracking Id

### ISSUE THREAD

**Issue by avner-hoffmann** [vacu/electron-google-analytics#15]
Hi,
The documentation doesn't specify the how and which tracking id should I create to start using google analytics
what tracking id should I create for electron app? I can only create tracking id for a website or a mobile app.
can you please explain?

**Comment by please-wait** [comment]
Website.

Use a subdomain (does not need to be active) of a verified domain to get your code. Put it in this library. Use the same subdomain for sending `pageview`.
