### ISSUE TITLE
With no session duration defined in pageviews call, pageviews fail to track at all

### ISSUE THREAD

**Issue by Galkon** [vacu/electron-google-analytics#18]
When you are tracking events using the suggested code examples, such as:

```GA.pageview('ApplicationName', '/' + path, path, clientId);```

The page views will never be tracked. You have to explicitly set the fourth parameter `sessDuration` as `undefined`, like so:

```GA.pageview('ApplicationName', '/' + path, path, undefined, clientId);```

Then all pageviews will be tracked properly. We experienced a major metrics issue due to this.

**Comment by alxmiron** [comment]
nice catch @Galkon 
we lost many tracking data too. need to be fixed

**Comment by vacu** [comment]
I've added "sessDuration" again as the 5th parameter so you can force start/end a session.
