### ISSUE TITLE
SyntaxError: Unexpected token o in JSON at position 1

### ISSUE THREAD

**Issue by athenawisdoms** [vacu/electron-google-analytics#23]
Hello, I am using `electron-google-analytics` in my Electron app that also uses React, Redux and Parcel. The `electron-google-analytics` instance is initialized using a *"web + app"* property, so it uses a Measurement ID starting with `G-` instead of a Tracking ID starting with `UA-`.

When I try to send any data to Google Analytics, such as `analytics.screen()` or `analytics.event()`, the response returned from calling the function is

> SyntaxError: Unexpected token o in JSON at position 1

Where did I go wrong? 

Additionally, when I use a Tracking ID instead of a Measurement ID, the same error occurs but at least the events are being recorded by Google Analytics. However, events logged using `analytics.screen()` does not appear to show up anywhere in the Google Analytics app. Does this module not work with Measurement IDs?

Thank you!

```
const analytics = new Analytics('G-XXXXXXXXXX');

analytics.set('clientID', state.user.clientId);
analytics.set('uid', state.user.uid);
analytics.set('appName', appName);
analytics.set('appVersion', appVersion);

// Intentionally passing these strings to `analytics.screen()`
const response = await analytics.screen('appName', 'appVersion', 'appId', 'appInstallerId', 'location.pathname');
console.log(response);
```
gives the following error in the electron app JS console

```
SyntaxError: Unexpected token o in JSON at position 1
    at index.js:591
```

![image](https://user-images.githubusercontent.com/6615285/80653039-34b7e700-8a47-11ea-840c-2df1b5491bcc.png)

*System Environment*
- electron-google-analytics@0.2.2
- electron@8.2.4
- parcel-bundler@1.12.4
- react-dom@16.13.1
- react-redux@7.2.0
- react@16.13.1
- node v14.0.0
- Mac OS X Catalina 10.15.3

**Comment by vacu** [comment]
Never saw LOC 590 before, maybe i'm wrong but isn't it ".catch((err) =>" ?

**Comment by vacu** [comment]
Couldn't generate a G-XXX id, that's the id it gave me with the app+web.

<img width="1451" alt="Screen Shot 2020-04-30 at 09 37 04 copy" src="https://user-images.githubusercontent.com/1682721/80679916-7e93e200-8ac6-11ea-8ee3-dc61e70ad202.png">
<img width="792" alt="Screen Shot 2020-04-30 at 09 40 09" src="https://user-images.githubusercontent.com/1682721/80679983-a420eb80-8ac6-11ea-8bfa-9409310f8b7f.png">

**Comment by vacu** [comment]
I will update the code later today for a better error message.
But to answer your question, it doesn't work.
Check https://ga-dev-tools.appspot.com/hit-builder/?v=1&tid=UA-XXXXX-Y&cid=555&t=screenview&an=funTimes&av=1.5.0&aid=com.foo.App&aiid=com.android.vending&cd=Home

**Comment by athenawisdoms** [comment]
@vacu Thank you! 

Did you manage to get a chance to push the commit that gives better error message, and maybe even publish this updated version to npm?

**Comment by vertangelx** [comment]
@vacu Any possibility that you will have some time to update the package with your fix for this problem? It will help tremendously with my problem as well. Many thanks!
