### ISSUE TITLE
Seeting up Google Analyltics

### ISSUE THREAD

**Issue by nickdima** [vacu/electron-google-analytics#4]
Thanks for working on this! I have a quick question. For using your lib one should set up the GA account as a website or as a mobile application?

<img width="618" alt="screen shot 2017-03-15 at 17 29 38" src="https://cloud.githubusercontent.com/assets/614468/23959374/54b8bd5c-09a5-11e7-93e8-9a45cb787636.png">

**Comment by nickdima** [comment]
I guess it works with both.

**Comment by sanjevirau** [comment]
Thanks a lot for this great stuff! @nickdima @vacu 
I would like to ask, is the GA tracking id is protected in electron?
I mean if I distribute my electron app, people can still view and steal the tracking id right?
